site:
  name: BLD Southeast
  site: 'https://bldsoutheast.com'
  base: '/'
  trailingSlash: true

  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: 'BLD Southeast 2026 - Washington, DC | September 16-17, 2026'
    template: '%s — BLD Southeast'
  description: 'Sept. 16-17, 2026. Join B Corps & mission-driven professionals in Washington, DC to learn & connect at the BLD Southeast conference.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: BLD Southeast
    images:
      - url: '~/assets/images/og-social-share-image.jpg'
        width: 1346
        height: 706
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
